services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - /AlfaBilling/
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - postgres_data:/AlfaBilling/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:8.4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 5050:80
    volumes:
      - pgadmin:/AlfaBilling/pgadmin/
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin: