services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /AlfaBilling/
    env_file:
      - .env
    container_name: alfa_back
    command: ["/AlfaBilling/docker/app.sh"]
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    volumes:
      - postgres_data:/AlfaBilling/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5438:5432

  redis:
    image: redis:latest
    restart: always
    environment:
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - 6379:6379
    volumes:
      - redis:/AlfaBilling/redis/

  pgadmin:
    image: dpage/pgadmin4:8.4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 5050:80
    volumes:
      - pgadmin:/AlfaBilling/pgadmin/
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin:
  redis: