services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - postgres_data:/AlfaBilling/data/
    env_file:
      - .env
    ports:
      - 5432:5432

volumes:
  postgres_data: