"""Created Operator, Client and Number tables

Revision ID: 234fa391fa7a
Revises: 
Create Date: 2024-10-13 23:20:54.805829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '234fa391fa7a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Client',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.Text(), nullable=False),
    sa.Column('Surname', sa.Text(), nullable=False),
    sa.Column('Patronymic', sa.Text(), nullable=False),
    sa.Column('Contract_number', sa.Text(), nullable=False),
    sa.Column('Passport', sa.Text(), nullable=False),
    sa.Column('Hashed_password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Contract_number'),
    sa.UniqueConstraint('Passport')
    )
    op.create_table('Operator',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.Text(), nullable=False),
    sa.Column('Surname', sa.Text(), nullable=False),
    sa.Column('Email', sa.Text(), nullable=False),
    sa.Column('Hashed_password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Number',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Phone_number', sa.Text(), nullable=False),
    sa.Column('Balance', sa.Float(), nullable=False),
    sa.Column('Client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Client_id'], ['Client.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Phone_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Number')
    op.drop_table('Operator')
    op.drop_table('Client')
    # ### end Alembic commands ###
