"""Create all-type Service tables

Revision ID: b09002d0d7b5
Revises: 234fa391fa7a
Create Date: 2024-10-17 01:28:16.261443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b09002d0d7b5'
down_revision: Union[str, None] = '234fa391fa7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addition_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=260), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('addition',
    sa.Column('service_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=260), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('is_unlimited', sa.Boolean(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['addition_category.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('service_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tarif',
    sa.Column('service_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=260), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('internet', sa.Integer(), nullable=False),
    sa.Column('is_unlimited_internet', sa.Boolean(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('sms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('service_id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tarif')
    op.drop_table('addition')
    op.drop_table('service')
    op.drop_table('addition_category')
    # ### end Alembic commands ###
