"""Create table schemas

Revision ID: c7d523190e83
Revises: 
Create Date: 2024-10-22 23:19:27.667963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7d523190e83'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addition_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=260), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('surname', sa.Text(), nullable=False),
    sa.Column('patronymic', sa.Text(), nullable=False),
    sa.Column('contract_number', sa.Text(), nullable=False),
    sa.Column('passport', sa.Text(), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_number'),
    sa.UniqueConstraint('passport')
    )
    op.create_table('operator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('surname', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('addition',
    sa.Column('service_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=260), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('is_unlimited', sa.Boolean(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['addition_category.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('service_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('number',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.Text(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('tarif',
    sa.Column('service_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=260), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('internet', sa.Integer(), nullable=False),
    sa.Column('is_unlimited_internet', sa.Boolean(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('sms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('service_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('activated',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activation_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('expiration_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('number_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['number_id'], ['number.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.Column('number_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['number_id'], ['number.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rest',
    sa.Column('internet', sa.Integer(), nullable=False),
    sa.Column('is_unlimited_internet', sa.Boolean(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('sms', sa.Integer(), nullable=False),
    sa.Column('number_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['number_id'], ['number.id'], ),
    sa.PrimaryKeyConstraint('number_id')
    )
    op.create_table('write_off',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.Column('activated_id', sa.Integer(), nullable=False),
    sa.Column('number_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activated_id'], ['activated.id'], ),
    sa.ForeignKeyConstraint(['number_id'], ['number.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('write_off')
    op.drop_table('rest')
    op.drop_table('payment')
    op.drop_table('activated')
    op.drop_table('tarif')
    op.drop_table('number')
    op.drop_table('addition')
    op.drop_table('service')
    op.drop_table('operator')
    op.drop_table('client')
    op.drop_table('addition_category')
    # ### end Alembic commands ###
